// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
var _url = "http://dev-sites.site90.com/yii/freeletics/";
require(_url + 'js/bootstrap/transition.js')
require(_url + 'js/bootstrap/alert.js')
require(_url + 'js/bootstrap/button.js')
require(_url + 'js/bootstrap/carousel.js')
require(_url + 'js/bootstrap/collapse.js')
require(_url + 'js/bootstrap/dropdown.js')
require(_url + 'js/bootstrap/modal.js')
require(_url + 'js/bootstrap/tooltip.js')
require(_url + 'js/bootstrap/popover.js')
require(_url + 'js/bootstrap/scrollspy.js')
require(_url + 'js/bootstrap/tab.js')
require(_url + 'js/bootstrap/affix.js')